
globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "JasmineMyco / %s"
og_image: /img/og_emma.png
author: Sorachai Sahabunyakool
favicon: /img/favicon.jpg
description: Personal blog of us
port: 8083

# OG image
origin: https://jasminemyco.com
og: /img/og.jpg


navigation:
  header:
    - JasmineMyco: /
    - Contact: /contact/

  footer:
    - © JasmineMyco: /

    - image: /img/twitter.svg
      url: //x.com/tipiirai
      alt: Twitter (X) profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/somtick
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/tipiirai
      alt: LinkedIn profile
      size: 22 x 22



